name: test

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:

  test-unit:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:

    # 소스 가져오기
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main

    # 노드 설치
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # 모듈 설치
    - name: Install Dependencies
      run: npm ci

    # 단위 테스트 jest
    - name: Test jest
      run: npm run test-jest
      

  test-e2e:

    runs-on: ubuntu-latest

    steps:

      # 소스 가져오기
      - name: Checkout source
        uses: actions/checkout@v2

      # e2e 테스트 cypress - chrome
      - name: Cypress run chrome
        uses: cypress-io/github-action@v2
        with:
          browser: chrome

      # e2e 테스트 cypress - chrome
      - name: Cypress run - firefox
        uses: cypress-io/github-action@v2
        with:
          browser: firefox