name: test-e2e

on:
  workflow_run:
    workflows: ["test-unit"]
    types:
      - completed

jobs:

  test-e2e:

    runs-on: ubuntu-latest

    steps:

      # 소스 가져오기
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Cypress run chrome
        uses: cypress-io/github-action@v2
        with:
          browser: chrome

      - name: Cypress run - firefox
        uses: cypress-io/github-action@v2
        with:
          browser: firefox

      - name: Cypress run - electron
        uses: cypress-io/github-action@v2
