name: test-e2e

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:

  test-e2e:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cypress run
        uses: cypress-io/github-action@v2
